direction: down

repos: Repositories {
	style.font-size: 50

	persistence: Persistence {
		shape: package
		style.font-size: 50

		store: FileDB {
			shape: cylinder 
			style.font-size: 50

			MapleCreated: {
				shape: class
				style.font-size: 50

				id: uuid
			}
		}

		ACL: "Anti\nCorruption\nLayer" {
			shape: circle
			style.font-size: 50
		}

		store <- ACL : store {
			style.font-size: 50
			style.stroke-width: 06
			style.animated : true
		}
		store -> ACL : retrieve {
			style.font-size: 50
			style.stroke-width: 6
			style.animated : true
		}

	}

}


logic: Logic  {
	style.font-size: 50
	domain:Domain {
		shape: package
		style.font-size: 50


		ACL: "Anti\nCorruption\nLayer" {
			shape: circle
			style.font-size: 50
		}

		memory: In-Memory Repository {
			shape: stored_data 
			style.font-size: 50

			MapleCreated: {
				shape: class
				style.font-size: 50

				id: uuid
			}
		}

		memory.MapleCreated <- ACL : retrieve {
			style.font-size: 50
			style.stroke-width: 6
			style.animated : true
		}
		memory.MapleCreated -> ACL : store {
			style.font-size: 50
			style.stroke-width: 6
			style.animated : true
		}
	}

}

logic.domain.ACL ->  repos.persistence.ACL: store{
	style.font-size: 50
	style.stroke-width: 6
	style.animated : true
}
logic.domain.ACL <-  repos.persistence.ACL: retrieve{
	style.font-size: 50
	style.stroke-width: 6
	style.animated : true
}


logic.domain.ACl -> Projectors.Maple_list{
	style.font-size: 50
	style.stroke-width: 6
	style.animated : true
}
logic.domain.ACl -> Projectors.redmaple_list{
	style.font-size: 50
	style.stroke-width: 6
	style.animated : true
}

projectors: Projectors {
	style.font-size: 50

	Maple_list: Maple List {
		shape: document
		style.font-size: 50

		list:List {
			shape: stored_data
			style.multiple: true
			style.font-size: 50

			Maple1: Maple 1 {
				shape: class 
				style.font-size: 50

				Maple_id: ID
				created_at: Time
				updated_at: Time 
				jouneys: '[]ValidID'
				contents: MapleContent
			}
		}

	}

	redmaple_list: redmaple List {
		shape: document
		style.font-size: 50

		list:List {
			shape: stored_data
			style.multiple: true
			style.font-size: 50

			redmaple1: redmaple 1 {
				shape:class 
				style.multiple: true
				style.font-size: 50

				redmaple_id: ID
				created_at: Time
				updated_at: Time 
				maples: '[]ValidID'
			}
		}
	}

}

commander: Command Handlers {
	shape: package
	style.font-size: 50
	create_Maple_command {
		shape: class	
		style.font-size: 50

		content: MapleContent
	}
}

commander.create_Maple_command -> logic.domain.ACL: request for change{
	style.font-size: 50
	style.stroke-width: 6
	style.animated : true
} 
commander.create_Maple_command <- logic.domain.ACL: status of message{
	style.font-size: 50
	style.stroke-width: 6
	style.animated : true
} 

querier: Query Handlers {
	shape: package
	style.font-size: 50

	get_maples {
		shape: class
		style.font-size: 50

		content: '[]Event'
	}

	get_redmaples {
		shape: class
		style.font-size: 50

		content: '[]redmaple'
	}

	
}

querier.get_maples <- projectors.Maple_list {
	style.font-size: 50
	style.stroke-width: 6
	style.animated : true
} 
querier.get_redmaples <- projectors.redmaple_list {
	style.font-size: 50
	style.stroke-width: 6
	style.animated : true
} 

UI: User Interface {
	style.font-size: 50
	height: 1500
	width: 1500
	
}

UI ->  commander.create_Maple_command : Requests a new_Maple {
	style.font-size: 50
	style.stroke-width: 6
	style.animated : true
} 

UI <-  commander.create_Maple_command : Gets Status of Delivery of Request  {
	style.font-size: 50
	style.stroke-width: 6
	style.animated : true
} 

UI ->  querier.get_maples : Request Information {
	style.font-size: 50
	style.stroke-width: 6
	style.animated : true
} 
UI <-  querier.get_maples : Respond Information {
	style.font-size: 50
	style.stroke-width: 6
	style.animated : true
} 




user : User {
	shape: person
	style.font-size: 50
	height: 1500
	width: 1500
	
}

user -> UI
user <- UI
